### ISSUE TITLE
XDR on currency code list

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Codelists#10]
This needs to be added, at some point

**Comment by Bjwebb** [comment]
This is an issue for https://github.com/IATI/IATI-Codelists-NonEmbedded

There's also the question of whether we want to manually add anything, or try to build an automatic process to do it.

**Comment by stevieflow** [comment]
Ah.  Can we reassign this issue ?

**Comment by Bjwebb** [comment]
No, it needs to be added. My question before we do so, is whether the issue is really 'XDR should be added' or whether it's really 'We should go through and update all external codelists'

**Comment by stevieflow** [comment]
We need the document circulating first of all imho - let's check this on Monday
