### ISSUE TITLE
Update TransactionType Codelist

### ISSUE THREAD

**Issue by allthatilk** [IATI/IATI-Codelists#112]
Make the following changes to the TransactionType Codelist:

**Update name:**
- [x] Code 2 new name: `Outgoing Commitment`
- [x] Code 5 new name: `Interest Payment`

**Update description:**

- [x] Code 3 new description: `Outgoing funds that are placed at the disposal of a recipient government or organisation, or funds transferred between two separately reported activities.`

- [x] Code 4 new description: `Outgoing funds that are spent on goods and services for the activity.`

**Add code:**

- [x] Code `12`
  - [x] Name: `Outgoing Pledge`
  - [x] Description: ` Indicative, non-binding advice of an intended outgoing commitment.`

- [x] Code `13`
  - [x] Name: `Incoming Pledge`
  - [x] Description: ` Indicative, non-binding advice of an intended incoming commitment.`

**Comment by stevieflow** [comment]
Isn't code 2 (Commitment - to be renamed as Outgoing Commitment) also in need of a description update?  This description is currently *exactly* the same as 11 (Incoming Commitment). 

This will be very confusing for people @bill-anderson

**Comment by PetyaKangalova** [comment]
@stevieflow

>  Isn't code 2 (Commitment - to be renamed as Outgoing Commitment) 

Yes, the code is being renamed. The current definitions for transaction type 2 and 11 are **not** exactly the same- see in [here](http://iatistandard.org/202/codelists/TransactionType/) and below. 

**2  -  Commitment (to be changed to outgoing commitment)**-   A firm, written obligation from a donor or provider to provide a specified amount of funds, under particular terms and conditions, for specific purposes, for the benefit of the recipient.

**11  -  Incoming Commitment**    A firm, written obligation from a donor or provider to provide a specified amount of funds, under particular terms and conditions, reported by a recipient for this activity.

**Comment by stevieflow** [comment]
OK thanks @PetyaKangalova 

My feedback (based on instances with users who have struggled to understand the "subtle" differences in definitions) is that the "from a donor" aspect for (Outgoing) Commitment is rather confusing.  Out + from don't sit well together.  

Equally, I dont see why we have to describe who *might* be making this commitments (a donor or provider) as that bleeds into specific contexts.  

Perhaps it could be:

> A firm, written obligation to provide a specified amount of funds, under particular terms and conditions, for specific purposes, for the benefit of the recipient.

(although that is not clear)

@PetyaKangalova is it better to surface this discussion on IATI Discuss?

**Comment by PetyaKangalova** [comment]
@stevieflow Yes,  I think it would be better to add to IATI Discuss.  Thanks!

**Comment by stevieflow** [comment]
See: https://discuss.iatistandard.org/t/outgoing-commitment-conflicting-description-use/1183
