### ISSUE TITLE
Indicator Measure Codelist should have text and NDP as options

### ISSUE THREAD

**Issue by caprenter** [IATI/IATI-Codelists#13]
Indicator Measure Codelist should have text as an option

Should also have NDP - NDP stands for Numeric Decimal Percentage

**Comment by Bjwebb** [comment]
Related to https://github.com/IATI/IATI-Schemas/issues/41

**Comment by Bjwebb** [comment]
Posted on the upgrades forum at http://support.iatistandard.org/entries/50136483-Add-NDP-to-IndicatorMeasure-codelist

**Comment by Bjwebb** [comment]
Closing this issue, as further discussion should happen on the forum.
