### ISSUE TITLE
1.04 Codelists

### ISSUE THREAD

**Issue by caprenter** [IATI/IATI-Codelists#14]
We need to take a look at this spreadsheet, and create some new codelists.
https://docs.google.com/spreadsheet/ccc?key=0AnWngmdQt3stdFNxVS1NdmpzSnR3aTBmUG1OWS1uZXc&usp=drive_web#gid=0
We may need to agree on naming conventions and how they fit into the SSOT.

**Comment by Bjwebb** [comment]
I believe this has now been done at https://github.com/IATI/IATI-Codelists/tree/1.04dev
