### ISSUE TITLE
TransactionType 12 and 13 should have `status` and `activation-date` attributes

### ISSUE THREAD

**Issue by andylolz** [IATI/IATI-Codelists#154]
On the [IATI Codelist Management](http://reference.iatistandard.org/203/codelists-guides/codelist-management/) page, the section “[Code status, addition and withdrawal dates](http://reference.iatistandard.org/203/codelists-guides/codelist-management/#code-status-addition-and-withdrawal-dates)” says:

> All new codes added to codelist from the release of version 2.02 (December 2015) will feature `status="active"` and `activation-date` attributes in the underlying GitHub source code repositories.

I think that means the newly added `TransactionType`s `12` and `13` should have `status` and `activation-date` attributes.

**Comment by samuele-mattiuzzo** [comment]
@IATI/bas anyone can take a look at this?
