### ISSUE TITLE
v2.03 bug: `transaction/aid-type` and `default-aid-type` mappings should include a `@vocabulary` condition

### ISSUE THREAD

**Issue by andylolz** [IATI/IATI-Codelists#169]
Originally raised [on IATI discuss](https://discuss.iatistandard.org/t/default-aid-type-for-activity-v-2-03/1480), so credit to @eimis for spotting it :clap:

---

In the [`transaction/aid-type/@code` v2.03 docs](http://reference.iatistandard.org/203/activity-standard/iati-activities/iati-activity/transaction/aid-type/#attributes), it currently says:

> This value must be on the [AidType codelist](http://reference.iatistandard.org/203/codelists/AidType/).

That’s not true, though. Since v2.03, the value is only required to be on the [AidType codelist](http://reference.iatistandard.org/203/codelists/AidType/) if the relevant aid type vocabulary (`1`) is used.

To fix this, [the v2.03 mapping.xml file](https://github.com/IATI/IATI-Codelists/blob/version-2.03/mapping.xml) should be amended to add a condition to the `aid-type` and `default-aid-type` vocabularies, similar to [the condition used for `sector`s](https://github.com/IATI/IATI-Codelists/blob/2e4d110dff05e03e82de90f892ceae28afe31462/mapping.xml#L305-L309).

**Comment by amy-silcock** [comment]
@PetyaKangalova please could you have a look through these tomorrow before we merge? And we'll see if rebuilding the iati-activities-schema.xsd pulls through the 2.03 added guidance onto the site :)

**Comment by amy-silcock** [comment]
This is now fixed and on the website. Good work all.

http://reference.iatistandard.org/203/activity-standard/iati-activities/iati-activity/default-aid-type/

**Comment by andylolz** [comment]
> This is now fixed and on the website.

Looks wrong on the website still. I’m expecting this:

> This value must be on the _[AidType codelist](http://reference.iatistandard.org/203/codelists/AidType/)_.

…to instead say:

> This value must be on the _[AidType codelist](http://reference.iatistandard.org/203/codelists/AidType/)_, if the relevant vocabulary is used.

When it says that, then it’s clear that the fix for this is working.

The IATI-Codelist submodule on IATI-Standard-SSOT was last updated a month ago, so that’s probably why. [Auto-deploying would save headaches.]

**Comment by amy-silcock** [comment]
@andylolz have a look now?

**Comment by andylolz** [comment]
Perfect! Thanks @amy-silcock.
