### ISSUE TITLE
Document better how the IATI-Codelist-NonEmbedded repository is used

### ISSUE THREAD

**Issue by caprenter** [IATI/IATI-Codelists#17]
This repo https://github.com/IATI/IATI-Codelists-NonEmbedded is required by IATI-Codelists and the SSOT, but it's not all that clear:

**Comment by Bjwebb** [comment]
I've made a start at this - https://github.com/IATI/IATI-Codelists/commit/78bee08d5e2a14d506a739167b0d3e1cf203917d
