### ISSUE TITLE
BUGFIX: Swap descriptions for activity status 3 & 4; clarify names (v2.0x)

### ISSUE THREAD

**Issue by andylolz** [IATI/IATI-Codelists#172]
This issue was raised and discussed here:
https://discuss.iatistandard.org/t/activitystatus-codes-mixup-of-descriptions-for-codes-3-4/304

The conclusion was that the descriptions for activity status 3 & 4 should be swapped. This was signed off by @bill-anderson here:
https://discuss.iatistandard.org/t/tag-session-on-reviewing-the-need-for-a-next-minor-or-major-iati-standard-upgrade/1535/8

**Comment by samuele-mattiuzzo** [comment]
👍

Just holding this for a while (hopefully no longer than a few hours), just to make sure we're merging the right bugfix here (description swap vs code swap vs potential name rename). We're going through the discuss posts and discussing this with Bill and the BAs (name for a new rock band?)

Fwiw, with my understanding, what you did to fix this (swapping the description) seems to be the most sensible solution, moving the most-open description before the most restrictive one, effectively giving meaning to `completion` and `post-completion` as they are (this is, again, just my opinion based on my understanding of it all)

**Comment by andylolz** [comment]
> discussing this with Bill and the BAs

+1, defo check with them. It would be good to get their verification that the fix applied here was the one agreed upon.

> name for a new rock band?

I’d buy the tee-shirt

**Comment by samuele-mattiuzzo** [comment]
Seems like the bug-fixing actioning has been agreed upon, but not on the actual solution. I think simply swapping the description around, albeit valid as per my previous comment, isn't complete (I think it would also require the names to be changed) nor is what has been agreed. Still awaiting for more clarification on the matter though, just updating since my last "hopefully it'll take a few hours"

**Comment by andylolz** [comment]
Hi @samuele-mattiuzzo,

No worries at all. I was maybe too keen to send these PRs. It might be quicker and easier to discuss at TAG. A bunch of the people on the discuss thread will be present, and can clarify / summarise far better than me. So, I’d suggest parking this until next week.

EDIT: Just to add: I do think consensus has been reached on this. But I think it will probably be beneficial for the actual final decision to be stated explicitly somewhere, just so we all have a clearer point of reference than the 50 post mega thread!

**Comment by samuele-mattiuzzo** [comment]
Tagged as incomplete for now, we'll reassess next week :)

**Comment by YohannaLoucheur** [comment]
Thanks Andy for following up with the pull request for the bugfix. It will be good to see this tidied up finally. 

Samuele said:
> simply swapping the description around, albeit valid as per my previous comment, isn't complete (I think it would also require the names to be changed) nor is what has been agreed.

The agreed solution is indeed to simply swap the descriptions for code 3 & 4, per Andy's pull request. 
The names don't *have* to be changed for the solution to be complete. Changing the names was indeed brought up in the post, as a potential additional change to clarify the codes; but the actual bugfix needed is swapping the descriptions for codes 3 & 4.  

Cheers

**Comment by samuele-mattiuzzo** [comment]
@andylolz have you seen this update? https://discuss.iatistandard.org/t/activitystatus-codes-mixup-of-descriptions-for-codes-3-4/304/65

Don't worry about re-sending the PRs (I saw you cancelled yours), we're on this now that a decision has been made!

**Comment by andylolz** [comment]
> Don't worry about re-sending the PRs (I saw you cancelled yours), we're on this now that a decision has been made!

^^ Ooops – only just read this! I’ve already re-sent PRs! :)

**Comment by andylolz** [comment]
> now that a decision has been made!

Apologies again for jumping the gun on this. It was my understanding that a decision had already been made, but I realise now I was a bit premature!

**Comment by samuele-mattiuzzo** [comment]
Yeah saw them 👍 will get on them asap :D

**Comment by samuele-mattiuzzo** [comment]
fyi, merging and deployment will not happen till next week so that we can give the community some grace time to read the post and all

**Comment by andylolz** [comment]
This looks fixed on production :clap: :rocket: :woman_astronaut:

Closing.

**Comment by andylolz** [comment]
I’ve just spotted that I didn’t apply this change to v1.0x. Obviously the description changes aren’t relevant there (since there were no descriptions until v2.01) but I guess the name change should be backported.

I’ve just sent PRs #199 and #200 to address this.

/cc @samuele-mattiuzzo.
