### ISSUE TITLE
Bug: codelists.xml and codelists.json include duplicate elements (all versions)

### ISSUE THREAD

**Issue by andylolz** [IATI/IATI-Codelists#183]
So for example, clv2 for v2.03:
 * http://reference.iatistandard.org/203/codelists/downloads/clv2/codelists.xml
 * http://reference.iatistandard.org/203/codelists/downloads/clv2/codelists.json

There are two copies of every item in these lists. This happens because the lists are initialised outside of the language for-loop, but appended to inside the for-loop. So we end up with a copy of the same information for each language (English and French):

https://github.com/IATI/IATI-Codelists/blob/e9b8f08203fce9d09777a88bd12c6407fa2dc157/gen.py#L6

https://github.com/IATI/IATI-Codelists/blob/e9b8f08203fce9d09777a88bd12c6407fa2dc157/gen.py#L32-L35

https://github.com/IATI/IATI-Codelists/blob/e9b8f08203fce9d09777a88bd12c6407fa2dc157/gen.py#L87-L89

A quick-fix solution would be to move the list initialisation inside the for-loop.

**Comment by samuele-mattiuzzo** [comment]
good catch, thanks Andy!

**Comment by andylolz** [comment]
This is fixed!
