### ISSUE TITLE
Make available a mapping from v1.0x to v2.0x embedded codelist codes

### ISSUE THREAD

**Issue by andylolz** [IATI/IATI-Codelists#190]
Some codelist codes were changed between v1.05 and v2.01. For instance TransactionType codes changed from being [alphabetic at v1.05](https://github.com/IATI/IATI-Codelists/blob/version-1.05/xml/TransactionType.xml) to [numeric at v2.01](https://github.com/IATI/IATI-Codelists/blob/version-2.01/xml/TransactionType.xml). The same is true for [OrganisationRole](https://github.com/IATI/IATI-Codelists/blob/version-1.05/xml/OrganisationRole.xml), [GazetteerAgency](https://github.com/IATI/IATI-Codelists/blob/version-1.05/xml/GazetteerAgency.xml) and [ActivityDateType](https://github.com/IATI/IATI-Codelists/blob/version-1.05/xml/ActivityDateType.xml). [Vocabulary](https://github.com/IATI/IATI-Codelists/blob/version-1.05/xml/Vocabulary.xml) codes were also changed in the same way, but were also split into two separate codelists.

IATI doesn’t define a mapping for these changes (not one that’s available programmatically, anyway). So in order to make use of data from different integer versions, these mappings must either be known or inferred. It would be useful if these mappings could be made available via the codelist API.

I think this only applies to the embedded codelists listed above. Non-embedded codelists are version-independent, so there’s no need for mappings.

**Comment by andylolz** [comment]
Here’s the mappings I was able to determine. Not sure if it’s exhaustive, but I think so.

## TransactionType
`C` -> `2`
`D` -> `3`
`E` -> `4`
`IF` -> `1`
`IR` -> `5`
`LR` -> `6`
`R` -> `7`
`QP` -> `8`
`QS` -> `9`
`CG` -> `10`

## OrganisationRole
`Accountable` -> `2`
`Extending` -> `3`
`Funding` -> `1`
`Implementing` -> `4`

## GazetteerAgency
`GEO` -> `1`
`NGA` -> `2`
`OSM` -> `3`

## ActivityDateType
`start-actual` -> `2`
`end-actual` -> `4`
`start-planned` -> `1`
`end-planned` -> `3`

## Vocabulary -> PolicyMarkerVocabulary
`DAC` -> `1`
`RO` -> `99`

## Vocabulary -> SectorVocabulary
`ADT` -> `6`
`COFOG` -> `3`
`DAC` -> `1`
`DAC-3` -> `2`
`ISO` -> null
`NACE` -> `4`
`NTEE` -> `5`
`RO` -> `99`
`RO2` -> `98`
`WB` -> null

**Comment by samuele-mattiuzzo** [comment]
Sounds like a sensible suggestion, will bring @PetyaKangalova into this to confirm what mappings are needed.

How would you suggest exposing this list? A `mapping_1_to_2.xml` of sorts, like the `dfid_mapping.xml` file? How do you see this being used? Just wondering if it needs a machine-readable way of being accessed or if it could just be a new page on the reference site (I reckon option no. 1 could be useful maybe for the future validator?)

**Comment by andylolz** [comment]
> How would you suggest exposing this list? A `mapping_1_to_2.xml` of sorts, like the `dfid_mapping.xml` file?

Yes exactly – that sort of thing. I’m not entirely decided on a recommended approach yet, though.

> Just wondering if it needs a machine-readable way of being accessed or if it could just be a new page on the reference site (I reckon option no. 1 could be useful maybe for the future validator?)

+1 for making this available in a machine-readable way. Humans can mostly infer these mappings already – for most of the codelist items listed above, the name is the same or similar between versions.

I suspect other user-facing products like d-portal already define these mappings somehow, e.g.:
https://github.com/devinit/D-Portal/blob/9c44e81e/dstore/js/dstore_db.js#L959-L971

OIPA probably defines all of them somewhere, I expect?

**Comment by andylolz** [comment]
v1.0x is deprecated now, so it’s unlikely this will happen. Closing.
