### ISSUE TITLE
Add new element to reflect codelist category

### ISSUE THREAD

**Issue by sargentfrancesca** [IATI/IATI-Codelists#204]
As per the codelist category update, add new metadata field to reflect the new categories in all codelists. In the case of this repository, the category value will be `Core`.

This can be completed as a script.

Please take into consideration versioning, and how codelists may have changed categories between versions.

**Comment by Ocre42** [comment]
Blocked until the new category names are defined and the redefined list is updated

**Comment by Ocre42** [comment]
Fixed
