### ISSUE TITLE
Question for our Community: is anybody using any of the scripts that are included within this repository?

### ISSUE THREAD

**Issue by samuele-mattiuzzo** [IATI/IATI-Codelists#240]
As per opening topic: any of you using the scripts included in here?

I'm keen on keeping them confined within the (new and in progress) `IATI-Standard-Reference-Site` (https://github.com/samuele-mattiuzzo/IATI-Standard-Reference-Site/tree/dev) so that `IATI-Codelist` stays content oriented (XML only, basically).

Is anyone currently using the scripts from within this repo to build anything out of it or can I move them out?

I'm looking at "we are using them actively for work purposes" rather than "we think in 5 years time they could be useful", as if that's the case we can think about it anyway in 5 years time 📟 

Pinging some usual iati-active suspects @andylolz @rory09 @rolfkleef @stevieflow @siemvaessen

Thank you all for your comments!

**Comment by andylolz** [comment]
> Is anyone currently using the scripts from within this repo to build anything out of it

[referencebot](https://github.com/referencebot) uses these scripts.

> or can I move them out?

I don’t mind. Referencebot was supposed be a tool that BAs could use / was supposed to demonstrate that it’s trivial to spin up new instances of the reference site. In practice, it isn’t really used, so I think it’s fine to break it.

**Comment by andylolz** [comment]
> so that IATI-Codelist stays content oriented (XML only, basically).

+1, I think this would be a move in the right direction.

I guess the main user of these scripts is the reference site itself. So I guess that means they shouldn’t be removed until the reference site is no longer reliant on them. (Apologies if I’m stating the obvious here).

**Comment by rorads** [comment]
I don't use them, so I have no issue with them being moved 😄 

If they're unlikely to be used anywhere else, then perhaps it would be sufficient to just stick them in a folder and note in a directory readme that any file references will need to have `../` put in front of them would do it? So something like:

```
IATI-Codelists/
├── .gitignore
├── etc
├── scripts/
│   ├── README.css
│   ├── script_1.py
│   ├── script_2.py
│   ├── script_N.py
│   └── etc
├── xml/
│   └── etc
└── etc
```

Mainly thinking this might save you some effort, but either way seems fine to me 😁

**Comment by samuele-mattiuzzo** [comment]
> Mainly thinking this might save you some effort, but either way seems fine to me grin

True, that was thought number 2, but thought number one is always along the lines of `if we do have a bug in one script, how many versions does it need checking and fixing on as well?` and so far the count has always tallied up to 6 at least

I know that we deprecated `v1.x` but I think (thanks to @andylolz for kickstarting this a wee few months back) abstracting build from content is absolutely necessary to move forward easily enough

**Comment by rolfkleef** [comment]
I don't use them, so fine with me.

Since these are the embedded codelists tied to a specific version of the standard, I'd be in favour of putting schema and codelists into a single repository.

**Comment by rorads** [comment]
Ah good point re: versioning - go ahead :)

[edit: removed email footer]

**Comment by andylolz** [comment]
Adding a reference here to IATI/IATI-Standard-SSOT#227

**Comment by samuele-mattiuzzo** [comment]
Thanks Andy. Haven't updated that one yet, but there will be updates about it soon.

Please let's not kickstart another conversation/argument there :)
Thanks to everybody for your responses and inputs, it's more than enough to go on with.

FWIW: the same "tidy up" job will be done on the SSOT branches as well, and the work for the split site has been carried on in one of my own GitHub repositories, will soon (will aim for EOW) move it under the IATI organisation.
