### ISSUE TITLE
mapping.xml is out of sync on different branches

### ISSUE THREAD

**Issue by andylolz** [IATI/IATI-Codelists#241]
#235; #237; #238 are good PRs, but they should all have been duplicated to other branches.

The SSOT & reference site have since been updated, so the mappings on the different versions are out of sync.

It would be good to rectify this.

**Comment by andylolz** [comment]
This is fixed for all v2.0x branches.

I haven’t attempted to address v1.0x branches.

If I did that work / sent those PRs, would they be considered?

**Comment by samuele-mattiuzzo** [comment]
I will ask the BAs what they reckon as well, imho it's not worth doing as we have dropped v1 and the reference guide has been archived, it's not used for validation etc

**Comment by andylolz** [comment]
> imho it's not worth doing as we have dropped v1 and the reference guide has been archived, it's not used for validation etc

Okay, cool. That works for me. ~~I’ll leave this for you to close if the BAs agree.~~ Closing.

Thanks!
