### ISSUE TITLE
File Format

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Codelists#26]
If this is a "partial" list - suggest we add open document formats to it:

http://dev.iatistandard.org/codelists/FileFormat/

In examples, I am citing .odt, for example

**Comment by Bjwebb** [comment]
According to http://www.iana.org/assignments/media-types/media-types.xhtml#application the following opendocument mimetypes exist:

```
application/vnd.oasis.opendocument.chart
application/vnd.oasis.opendocument.chart-template
application/vnd.oasis.opendocument.database
application/vnd.oasis.opendocument.formula
application/vnd.oasis.opendocument.formula-template
application/vnd.oasis.opendocument.graphics
application/vnd.oasis.opendocument.graphics-template
application/vnd.oasis.opendocument.image
application/vnd.oasis.opendocument.image-template
application/vnd.oasis.opendocument.presentation
application/vnd.oasis.opendocument.presentation-template
application/vnd.oasis.opendocument.spreadsheet
application/vnd.oasis.opendocument.spreadsheet-template
application/vnd.oasis.opendocument.text
application/vnd.oasis.opendocument.text-master
application/vnd.oasis.opendocument.text-template
application/vnd.oasis.opendocument.text-web
```

Of these, I propose that only the following 3 are added to our list (since they're the most common and also in line with the microsoft file formats on the list):

```
application/vnd.oasis.opendocument.presentation
application/vnd.oasis.opendocument.spreadsheet
application/vnd.oasis.opendocument.text
```

**Comment by stevieflow** [comment]
So
format="application/odt"

should be

format="vnd.oasis.opendocument.text" ?

**Comment by Bjwebb** [comment]
No, it should be:

> format="application/vnd.oasis.opendocument.text"

**Comment by Bjwebb** [comment]
All the open document mimetypes should start with `application/` btw. I've updated my previous comment to reflect this.

**Comment by stevieflow** [comment]
Added these to: https://github.com/IATI/IATI-Extra-Documentation/tree/organisation-standard

@Bjwebb does this mean that other format examples on this codelist could be incorrect?

**Comment by Bjwebb** [comment]
All the other examples look to be correct.

**Comment by Bjwebb** [comment]
If we add the open document formats to our list, we should probably also add the newer microsoft formats.
e.g.

```
application/vnd.openxmlformats-officedocument.wordprocessingml.document
application/vnd.openxmlformats-officedocument.spreadsheetml.sheet
application/vnd.openxmlformats-officedocument.presentationml.presentation
```

**Comment by Bjwebb** [comment]
This issue will be moot if we import all of the codes from the IANA list https://github.com/IATI/IATI-Codelists-NonEmbedded/issues/7

**Comment by Bjwebb** [comment]
This issue is now no longer relevant now that we've imported the full list.
