### ISSUE TITLE
Add Full Descriptions To All Codelist Values

### ISSUE THREAD

**Issue by wendyrogers** [IATI/IATI-Codelists#3]
Raised from Zendesk ticket #898.

Please develop a set of fuller descriptions to describe the values and also when each value should be used.

**Comment by bill-anderson** [comment]
What are you asking me to do?

**Comment by Bjwebb** [comment]
@bill-anderson To write/review descriptions for codes on Embedded codelists (much like you did for schema descriptions). Alternatively, to decide whether we should do this for 2.01, or whether it should be part of a future upgrade.

**Comment by bill-anderson** [comment]
All????????
This will take a day next week sometime

**Comment by Bjwebb** [comment]
@bill-anderson Yes, I'm aware that this is a big task. I think it's up to you to decide what should be done, and when. It's possible some of this task could be done by someone else, but it would likely involve asking you lots of questions.

**Comment by caprenter** [comment]
@bill-anderson This is set as a task for the 2.01 Iteration 3 milestone - now due in a few days.
What's the plan?

**Comment by bill-anderson** [comment]
I am not in a position to do this in the next week. I suggest that @stevieflow and @iatisupport work on it and I can review at the end of next week.

**Comment by caprenter** [comment]
@bill-anderson Changes to Embedded codelists can only occur during the change control process. 
(Changes to non-embedded ones could be brought up as a separate issue) 
IMHO I think this means this cannot now happen in 2.01

**Comment by bill-anderson** [comment]
If we were talking about codes, or substantive changes to the meaning of codes, I would agree. Improving wording of descriptions is a grey, less-critical area. I think we can put 'fixes' through during the final processes

**Comment by stevieflow** [comment]
@izzirbucknall will look into this

**Comment by Bjwebb** [comment]
See the bottom of http://support.iatistandard.org/entries/52106609-Version-2-01-Iteration-3-8-Miscellaneous for the 2.01 proposal for this.
