### ISSUE TITLE
FlowType - code 40

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Codelists#31]
http://dev.iatistandard.org/codelists/FlowType/

Code 40 `Non flow` might want the (eg GNI) moving to description rather than name

In terms of descriptions, these are not present in the latest DAC codelist

**Comment by Bjwebb** [comment]
@bill-anderson Do you know where the descriptions are from?

What should we do about these descriptions?

(Also note this is a NonEmbedded codelist, so this is not actually a 1.05 change per se).

**Comment by bill-anderson** [comment]
I can only assume they come from an earlier version of the list in the dac spreadsheet. Standard rules apply: they need to be changed to match the current authority list
