### ISSUE TITLE
CollaborationType - missing code 7

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Codelists#32]
Code 7 on DAC codelist:

7   Bilateral, ex-post reporting on NGOs’ activities funded through core contributions

**Comment by Bjwebb** [comment]
Do you have any information about when this code was added?

Also, bugs about non-embedded codelists would probably be best reported against that repository https://github.com/IATI/IATI-Codelists-NonEmbedded/issues?milestone=1&state=open

**Comment by stevieflow** [comment]
OK - shall I log that there instead?

There was an issue here: http://support.iatistandard.org/entries/21871373-Collaboration-Type-Code-List - but nothing about code 7.  Any insight @bill-anderson ?

**Comment by bill-anderson** [comment]
7 = Bilateral, ex-post reporting on NGOs’ activities funded through core contributions

Seems to have been around for some time. Definitely not new

**Comment by Bjwebb** [comment]
Should it be added?

I guess the appropriate place to post this is now http://support.iatistandard.org/forums/23076626-Non-embedded-Codelist-Amendments

**Comment by bill-anderson** [comment]
Yes, and yes

**Comment by stevieflow** [comment]
Have added: http://support.iatistandard.org/entries/96520726-Collaboration-Type-addition-of-code-7

@bill-anderson any idea what "ex-post reporting on NGOs’ activities" means?

**Comment by bill-anderson** [comment]
http://www.investopedia.com/terms/e/expost.asp
