### ISSUE TITLE
codelists.xsd exists in all branches

### ISSUE THREAD

**Issue by caprenter** [IATI/IATI-Codelists#34]
Not sure if this is an issue or not, but now that we have a branch for each version of the standard then the codelists.xsd ends up being versioned with that version of the standard. I don't think this is what is intended.

Instead the codelist.xsd should be version controlled by itself?

Came across this as https://github.com/IATI/IATI-Codelists/blob/master/codelist.xsd 404's - reported https://github.com/IATI/IATI-Websites/issues/97

**Comment by Bjwebb** [comment]
I think it belongs in the Codelists repository. Although it has some problems, it makes sense to version the changes of it along with the standard.
