### ISSUE TITLE
ISO Country Codes are out of date

### ISSUE THREAD

**Issue by bill-anderson** [IATI/IATI-Codelists#37]
http://dev.iatistandard.org/codelists/downloads/clv2/csv/en/Country.csv contains 

PS - PALESTINIAN TERRITORY, OCCUPIED

This should be 

PS - Palestine, State Of

(and https://www.iso.org/obp/ui/#search isn't all upper case)

**Comment by Bjwebb** [comment]
Yes, this should be fixed once I pull from the ISO XML directly - https://github.com/IATI/IATI-Codelists-NonEmbedded/issues/8 -  I hope to be able to look into this next week.

**Comment by caprenter** [comment]
It's worth remembering that we don not yet have an agreed process on how we update non-embedded codelists and how we communicate those changes.

I would suggest that the steps would include:
1) Being made aware of a change
2) Agreeing what change should be made, and when it should happen (internally/externally/with or without an announcement ?)
3) Implementing (and testing) the change
4) Logging that a change has been made (allowing people to track changes)
5) Announcing the change

but of course that's just a starting point.

**Comment by stevieflow** [comment]
Is this issue still live?

**Comment by Bjwebb** [comment]
Yes. I've not had chance to finish my work around pulling external codelists yet.

**Comment by Bjwebb** [comment]
This should be fixed when https://github.com/IATI/IATI-Codelists-NonEmbedded/pull/51 is merged.

**Comment by amy-silcock** [comment]
ISO Country Codelist is up to date as of July 2018: http://reference.iatistandard.org/203/upgrades/nonembedded-codelist-changelog/
