### ISSUE TITLE
No link from codelist to codelist API page

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Codelists#38]
This would be important to help clarify the difference between CLv1 and CLv2 

eg: http://iatistandard.org/codelists/ActivityStatus/ - no link to 

http://iatistandard.org/codelists/codelist-api/

**Comment by stevieflow** [comment]
In this context, we might also be able to elaborate/clarify on the labels `Current` and `New`

**Comment by Bjwebb** [comment]
There is now a link: http://dev.iatistandard.org/codelists/ActivityStatus/

I've created a separate issue for elaborating/clarifying the current/new labels https://github.com/IATI/IATI-Extra-Documentation/issues/191
