### ISSUE TITLE
Implement 2.01 "Vocabulary Codelists"

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Codelists#43]
http://support.iatistandard.org/entries/78019646-Separate-vocabulary-codelists

**Comment by Bjwebb** [comment]
So far the Vocabulary codelist has been renamed SectorVocabulary. Still to do
- [x] Add a new PolicyMarkerVocabulary codelist
- [x] Remove non-sector related items removed from the SectorVocabulary codelist.

**Comment by Bjwebb** [comment]
@bill-anderson Which codes should remain on the [SectorVocabulary codelist](http://dev.iatistandard.org/201/codelists/SectorVocabulary/)? I know we want the two DAC codes on there, and Reporting Org specific, but what about the others?

**Comment by Bjwebb** [comment]
BTW, current use can be seen on the dashboard: http://dev.dashboard.iatistandard.org/codelist/sector_@vocabulary.html

Not sure how useful this is, as some people seem to be using AidData as a sector vocabulary, when I'd heard it said it was only used for policy markers.

**Comment by Bjwebb** [comment]
@bill-anderson Could you also check whether the [PolicyMarkerVocabulary codelist](http://dev.iatistandard.org/201/codelists/PolicyMarkerVocabulary/) has al the items it should. Specifically, what is the vocabulary corresponding to our [PolicyMarker](http://dev.iatistandard.org/201/codelists/PolicyMarker) list? (I think it's an IATI maintained list based on DAC columns, so I'm not sure what we should Name the code)

**Comment by bill-anderson** [comment]
SectorVocabulary 
1 - OECD DAC CRS Purpose Codes (5 digit)
2 - OECD DAC CRS Purpose Codes (3 digit)  
3 - Classification of the Functions of Government (UN)  
4 - Statistical classification of economic activities in the European Community
5 - National Taxonomy for Exempt Entities (USA)  
98 -Reporting Organisation 2 
99 - Reporting Organisation

PolicyMarkerVocabulary
1 - OECD DAC CRS
99 = Reporting Organisation

**Comment by Bjwebb** [comment]
I've now made this change:
- http://dev.iatistandard.org/201/codelists/SectorVocabulary/
- http://dev.iatistandard.org/201/codelists/PolicyMarkerVocabulary/

Remaining tasks:
- [x] @bill-anderson Do we need to communicate more explicitly (on the support forum) that the AidData, ISO and World Bank codes have been removed as a result of this change.
- [x] Update the French translations based on your updated names for some of these codes (not sure whose this responsibility is)

**Comment by bill-anderson** [comment]
" @bill-anderson Do we need to communicate more explicitly (on the support forum) that the AidData, ISO and World Bank codes have been removed as a result of this change."

I have just looked at dashboard ...
- Third parties are using Aiddata so I think we should leave it in
- ISO and World Bank are only being used in error so I would get the two publishers to fix their data
- World Bank itself is using invalid codes at the moment (not 'WB') - they will need to move to R0 and R02
- in the light of this I don't think we should communicate any more as it is going to create confusion with the World Bank. 

I don't think french translations needs to be my responsibility

**Comment by Bjwebb** [comment]
@bill-anderson To clarify, AidData should be on the SectorVocabulary codelist, and not the PolicyMarkerVocabulary codelist?

**Comment by bill-anderson** [comment]
Yes

**Comment by caprenter** [comment]
I understand that the outstanding task here is to update the French translations on the SectorVocabulary codelist: https://github.com/IATI/IATI-Codelists/blob/version-2.01/xml/SectorVocabulary.xml

As this task is currently unassigned, assigning to Bill to decide who it should actually be assigned to!

**Comment by caprenter** [comment]
There is a request into UNOPS to help with this. Re-assigning to new milestone
