### ISSUE TITLE
Review names/descriptions of codelists and codes

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Codelists#45]
These all need checking really, but some specific issues are:
- [x] Inconsistent usage of "OECD Development Assistance Committee" vs "OECD DAC"
- [x] [OrganisationRole](http://dev.iatistandard.org/201/codelists/OrganisationRole/) is described as "The categories of DAC Sector codes". Is this correct?

**Comment by bill-anderson** [comment]
"OECD" and "DAC" should be in glossary and not spelled out elsewhere

**Comment by Bjwebb** [comment]
@bill-anderson [OrganisationRole](http://dev.iatistandard.org/201/codelists/OrganisationRole/) is described as "The categories of DAC Sector codes". Is this correct?

**Comment by bill-anderson** [comment]
"AN IATI code for the role of an organisation within an activity. An organisation can play more than one role within an activity."

**Comment by Bjwebb** [comment]
In terms of generally reviewing codelist descriptions, it seems this has been raised before: https://github.com/IATI/IATI-Codelists/issues/3
