### ISSUE TITLE
Activity Status - Suspended

### ISSUE THREAD

**Issue by bill-anderson** [IATI/IATI-Codelists#47]
http://support.iatistandard.org/entries/43247528-Activity-Status-Suspended-

@bill-anderson to add note of warning on forum re: forward-looking budget calculations

**Comment by bill-anderson** [comment]
done

**Comment by Bjwebb** [comment]
I've added suspended to the list.

@bill-anderson All the other codes on that list have French translations of the names, do we need one for "Suspended" too. If so, who should we ask to translate it?

**Comment by caprenter** [comment]
@Bjwebb To complete this task, we need to 
- [x] cherry pick this commit and add it to the 1.05 branch
- [x] get the translation in place (I have asked on the forum)
- [x] ensure the change is reflected in the changelog(s)

**Comment by Bjwebb** [comment]
I mistakenly added this to the 2.01 milestone and branch, when I thought it should be 2.01. As such, you're right, it needs cherry picking onto the 1.05 branch. (Doesn't need removing from the 2.01 branch as all 1.05 changes will be merged in before going live anyway).
