### ISSUE TITLE
Review the numbering of all newly numeric codes

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Codelists#48]
Steven made a [comment about the ActivityDateType numbering](http://support.iatistandard.org/entries/41042407-Modify-code-list-activity-date-type-Language-neutral-conversion#view-post-25992316), but we should check the other codelists too:

http://dev.iatistandard.org/201/codelists/ActivityDateType/
http://dev.iatistandard.org/201/codelists/GazetteerAgency/
http://dev.iatistandard.org/201/codelists/OrganisationRole/
http://dev.iatistandard.org/201/codelists/TransactionType/
http://dev.iatistandard.org/201/codelists/SectorVocabulary/

(Issue for the change to numeric: https://github.com/IATI/IATI-Codelists/issues/25)

**Comment by Bjwebb** [comment]
@bill-anderson Could you review the new numbering used for each of these codelists?

**Comment by Bjwebb** [comment]
Another proposal might be to ensure that the default value for a Vocabulary is always numbered 1. ie. that SectorVocabulary has code 1 as 5 digit DAC codes. Note that SectorVocabulary probably also has too many codes on it, see https://github.com/IATI/IATI-Codelists/issues/43

**Comment by bill-anderson** [comment]
Agree with 1 = default value. Not fussed about others. I'm sure @stevieflow will have a grand plan

**Comment by stevieflow** [comment]
The concern with `ActivityDate` was that the numeric codes may not have "flowed".  Granted, this may seem arbitary, but we might want to decide whether to order the numbers by date period (start dates, then end dates) rather type (actuals, then planned)....

**Comment by Bjwebb** [comment]
Renumbered SectorVocabulary in [this commit](https://github.com/IATI/IATI-Codelists/commit/8416c68080b28ed236dff5989ba77559160c6ba2). I've glanced through the other codelists, and the only other potential issue I spot is [OrganisationRole](http://dev.iatistandard.org/201/codelists/OrganisationRole/) now has Accountable as code 1 (because I numbered them alphabetically), but Accountable is actually one of the less used codes.

@stevieflow I agree that ActivityDate might also be useful numbered more chronologically. How about:
- 1- start-planned
- 2 - start-actual
- 3 - end-planned
- 4 - end-actual

**Comment by stevieflow** [comment]
ok thanks 

Agree with the new numbers for `ActivityDateType`

@bill-anderson any thoughts on `OrganisationRole` ?

**Comment by stevieflow** [comment]
Looking at `OrganisationRole` - @bill-anderson 

http://dev.iatistandard.org/201/codelists/OrganisationRole/

Could these be in a different order, perhaps?:

Funcing
Accountable
Extending
Implementing

**Comment by bill-anderson** [comment]
Could be. I agree with whatever you think is best

**Comment by stevieflow** [comment]
Definitive answer!

1 Funding
2 Accountable
3 Extending
4 Implementing 

seems more in line with "flow" than:

1 Accountable
2 Extending
3 Funding
4 Implementing 

? @jonihillman @iatisupport ?

**Comment by wendyrogers** [comment]
Definitive answer looks about right to me!

**Comment by stevieflow** [comment]
Do we take the revised order as a change for @Bjwebb to implement therefore?

**Comment by bill-anderson** [comment]
As he said - "I agree with whatever you think is best"

**Comment by stevieflow** [comment]
Assigned to @Bjwebb to implement

**Comment by stevieflow** [comment]
@Bjwebb I have created new Issues for the three codelists that need renumbering

Aside from that, the only comment I can see in this Issue that may need some action is https://github.com/IATI/IATI-Codelists/issues/48#issuecomment-54337024 - is this correct (or can we close this?)?

**Comment by Bjwebb** [comment]
I think this issue can now be closed.
