### ISSUE TITLE
Poor translation on Vocabulary codelist

### ISSUE THREAD

**Issue by caprenter** [IATI/IATI-Codelists#60]
The translation of RO name into French is not very good:
"Reporting Organisation (i.e. maintained by the organisation referred to in the &lt;reporting-org&gt; element." 
translates as:
"Organisation déclarante (i.e. maintained by the organisation referred to in the &lt;reporting-org&gt; element."

**Comment by caprenter** [comment]
See also; https://github.com/IATI/IATI-Codelists/issues/43

**Comment by caprenter** [comment]
There is request for help on this with UNOPS

**Comment by caprenter** [comment]
While UNOPS have helped with translations on version 2.01, this has not been addressed specifically.

So the issue remains as reported initially.

**Comment by YohannaLoucheur** [comment]
A colleague just signaled that the translation for the Related Activity Type codelist is somewhat funny.  
It was translated as: 
parent: mère (mother)
child: fille (daughter)
sibling: jumelle (female twin)

We would suggest more neutral terms:
parent: parent
child: descendant
sibling: fratrie

**Comment by rorads** [comment]
Thank you for pointing this out, Yohanna. That does look a little off! I will incorporate your suggestions asap.

Thanks,
Rory

**Comment by hayfield** [comment]
Updated in 1c3d0623f3d50e9ffb53604f59690f10e55b9ceb and #98
