### ISSUE TITLE
Renumber ActivityDateType codelist

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Codelists#65]
From https://github.com/IATI/IATI-Codelists/issues/48#issuecomment-54337024

```
1- start-planned
2 - start-actual
3 - end-planned
4 - end-actual
```

**Comment by Bjwebb** [comment]
I will also fix the descriptions at the same time: https://github.com/IATI/IATI-Codelists/commit/33b2174f8c2aeb42f277f8ad9d715b31233179bc#commitcomment-7837759

**Comment by stevieflow** [comment]
New ticket created in terms of updating the activity-date rules: https://github.com/IATI/IATI-Extra-Documentation/issues/291
