### ISSUE TITLE
Add OtherIdentifierType codelist - descriptions

### ISSUE THREAD

**Issue by Bjwebb** [IATI/IATI-Codelists#67]
http://support.iatistandard.org/entries/52824355-Version-2-01-Iteration-3-9-Organisation-and-Activity-Identifiers

**Comment by Bjwebb** [comment]
- [ ] The codelist should also have descriptions for the codes.

**Comment by Bjwebb** [comment]
- [x] Swap A1 and A2 https://github.com/IATI/IATI-Schemas/issues/228#issuecomment-56534954

**Comment by stevieflow** [comment]
@izzirbucknall this is a new codelist.  Do you think you could add the desription text via the spreadsheer?

**Comment by caprenter** [comment]
These descriptions will not be written by original milestone of 2.01 Final so moved to 2.01 Release Date milestone

**Comment by hayfield** [comment]
This was not undertaken for `2.01`.

A full review of missing / questionable Code descriptions should be undertaken as a patch upgrade.

@IATI/bas
