### ISSUE TITLE
PolicyMarkerVocabulary codelist missing a value?

### ISSUE THREAD

**Issue by stevieflow** [IATI/IATI-Codelists#94]
Guidance on [Humanitarian Reporting](http://iatistandard.org/202/activity-standard/overview/humanitarian-reporting/) states:

> PolicyMarkerVocabulary - code "2" defines the list of UNOCHA humanitarian policies to which a specific activity relates.

However, this Codelist [seems to be missing a code 2](http://iatistandard.org/202/codelists/PolicyMarkerVocabulary/) (I think)

**Comment by hayfield** [comment]
The referenced guidance was removed in IATI/IATI-Extra-Documentation#320.
