### ISSUE TITLE
Improve descriptions of Transaction Types for Incoming Commitment & Commitment

### ISSUE THREAD

**Issue by wendyrogers** [IATI/IATI-Codelists#95]
It has been requested that we make the descriptions and differences between an Incoming Commitment and Commitment more explicit and clearer on the Transaction Type codelist at http://iatistandard.org/202/codelists/TransactionType/

**Comment by hayfield** [comment]
This is to occur with `2.03` through the changing of the name of `Commitment` to `Outgoing Commitment`.

See: #112

**Comment by stevieflow** [comment]
Isn't the description also in need of an update too, though (they are currently the same)?

**Comment by stevieflow** [comment]
I dont believe this should be closed.  The descriptions of these have not been worked on, only the names: https://discuss.iatistandard.org/t/outgoing-commitment-conflicting-description-use/1183
